language: node_js
sudo: false
node_js:
- 8.9.4
install:
- npm install
script:
- npm test
env:
  matrix:
  - secure: uJvsaPEItGteXS72d3jP5us7PvR0Uf5lqd5T7U8jmTAfnNYtI/1R+SurskXCLwz9PXbZ3mh2WdYLFx062C7vJkKAnQxDWUeLSt+fuBmhYiWsc0i9Qr2ikWImwDcg9ikmjxUJHM/YOA5C975YFevTHnFQIBMU40ErAUut3CUwfOEL70YkS6dvTxO1hy+psV5tJHfTAenBaMXHcGRZeVWr/MbnAqoIGqjBXkprt7IZtCBGYysFdY1tTHU9udeT7t7D5FqRTL3rN3r/Ib6b4652Xi2h/SDBv+v4x4/hHs3p1ADxekhqLumztGAbXtBxE0vRi2XEbe4EAsoGOy+gmmcdSTLlfU4uxh65aBHVYAOLSdXlmt+fGPH5IgdD1dd/L3p8R9JAyXx+1XSHtGfkGjjqfONKLcG2KKLHX1NTqyFdnsAPVv7A9kQJVSogdaVMB7ur2YsQR/4qI25bg7QtctgkGk5KgSnM5ZhHR4GBygJbZY0Qe2H8g8Ecx9BHlGtCMPpl2j4aBoGNK8lnz4NBjlNbaWqT3PWPAOH11rRfoxNSFP1Y6DoE5ZyVmYj28eioy0/qclSK9hpm4KO2H1HtkJ8138PqHBjuOpHMusEr8ILcxz9P3FgDkRP3wcZpluPK/7r6BI7tYMI+6kXM7VbtzpG6bOUFWHEEDBwXotZbe1aeSOI=
deploy:
  provider: heroku
  api_key:
    secure: hsp2t+cEM+DWIZ+H3b5BQcf0OOsQ1dzvoTMEyv6uRjMuUXX+Pvsu582Gt1sjfPvtC32L8kLMajE07VnIJswyVg/U/z1uv6VAFcSpv5CHvULHazlZYZsbrMDfZo1AYgZMpDgc8stgwen7zUunY5J4CWJjZe5N7dcevUXr2Edv4jYf8U2zjGSo2oVjsMokqsne0JDdXElKmAnczWq4ZBLh6yAcqm1Djfm5lPyin6EcaW35i1J6OI7z2nUE08b1DNEW9JyW+oT0/idcDppCXToAscpGEn0MApjf9FJIMxSBPJx9Ubcwap8h1HiSLSzmB/y5xybdoNpSHcNvvIbaxhmwi1r0FN5vRPcNuiL9oOYBbZhttD/066WLuM9kX1GzOJ6XEdIFYujLufA7f7UvljsdTQLJZJEjtFxrAemcMVsy0zYQqyP1IYiNTSC6K819Oo/cDYpBM7jASICWnkYx3W8ojhktzBuRgvFHGYsmyJAR2VqDpyeSHITd1NZmwSa2EUmGlgVNBE5LC9H7tqU9XY3k1fp/Rd0P/cia+UJt53XT2Bk+hBVX1GWECS2MONu0jI1B+Igx7njMJSK+Xb8z4lEqwoHv5cqOB8OyqNzZajI6hWRLjRQ6HWMZe7ilYfKnnS7CMQgTA36mRoxTln5EI2XlUDrNsi2JZYceazUqOg6xkNs=
  app: ft-tech-test
  on:
    repo: Leigan0/test
