language: node_js
sudo: false
node_js:
- 8.9.4
install:
- npm install
script:
- npm test
env:
  matrix:
  - secure: doReTg63wiEmdKOp80Cj/Uop+0Jp+3LvjLK8Fy/J1TMwyEUjx51KQhilXo/x0Xhuw6DlTT/VPSeyIeksIHRxnpwpOT3UeKxiUwyYv3qiPczjItHr+nIMcbhzFJw52dlGTReAVj16Hzk7yoa6ZH7XCgACJN8htgDHD1jT3q7gwuoYEc59jxZAWpTnlRg/iyIK3q61fGIHFRGf8zkgbKj1xkp1qja8tnE3ZRn2UKOeQP11IeWJq+S4u+R9J7dARHMJGWPuOYvjo+eloe+tGFWJi1CF9niyNmCe/B4N95uNdEHpThQn/BOSiAEV8tdh18FEeaaChMTrc+3KEvXiJ49X5LFO+JGCyyiq7BhYMQpK7lhLWvcGQsO8dMZp499rLMC3XaXKr+YveTh39kTAf6rYnP7fZkWWfLNYpFfGJo9+PFNmfSAsyXOiSJNKwtIIH+angRP+bETGcNA7nohY7R05GRyFjtGi+WaYvWjI9thvk/TwUOi28wnrRAqKX1p//+nn1ZpDVU8FRlZrw+FalE5f9+AnFlLqBlgV16EOU8Wx2/b0M1lLws+h1MQxj1tumXP3rCPvHLJJZXete2VWs8nh0LP3dcHmcC/I9nlfzjtYheTx+l4Dm7Dekk0rKWyC8Y5bQ9LA8cbqKlWiJhbaFb8Pf9XVfuT9i2ml000Gf0RabgU=
  - secure: UGDQehmmJdfeeeHk26nuFjVUINsahvxKNQuJW80ovudg/PsP/2WwzysjLzvSgjgKWFJttTClSJh4Ree59h9lOnt4xCa9H5IPNyHIrhxY6zxDdHmEc7p5rbULVL0WXmBnM+eB07YlnXxNlbhjh2orE8ZvaJKhyEu3yaiMBni6lFtO9AvOqpUTL86nVIyDH15GCBdS4FW8ejiy2hP9gpwivQeXnNDpb7Zb+4i/Y9P/c3tecEAn+9W+nhb4s95DAPti0S0kPZZHhNtf082xcK68aPt/pkM0MB8ONeyS66qxUUU1cNfGpKybPKj0jYBu4/KHFjHI2T1nLVifA6G0QYL7uTAvRKdz4ljYVFD6xB5R5BNXjLtUwQoCqtq+6l1tN5hNpjyUDeO+ftfSWbIi4GFyDJGhkXqxF76+MZoXi6rhzrBM8crefX6eVzAYQ6TqE7B3asoohKEfqy0XroHaOHwkmuuVbz+Fi2jxEJwptLZVXJdoudBVIy4DQcq1SqlPjgMrYn31HA8Lh+mxQ19I39Df9EdmvmuKpAwRABdWT68dH+F9ynhU5Apgedb0meE4GnVfww6f2rgsizM1bJXYPlWEpK/4Wt0DtZYLiHCh6b2YKvI2S5RoBylE7iHhUvWtozGwrFA8K1Sb1LkihYpIQukLweQGdo/0azr5y2aOW0XoHoo=
