language: node_js
sudo: false
node_js:
- 8.9.4
install:
- npm install
script:
- npm test
env:
  matrix:
  - secure: aqFkXegnERBGlArlBl3cuMCeeSfsh1A8Hadn5hHcNd0jOfktG766+kZT12gDFQGUhuWldOGv+kDdG8kIFniz1xMMSRmCi4YK2W8FCkpm4Bp2yjSfb7PWCicNCD67Wirc7ontQdWXzy+qeTzDmz7D/H4ZE6++R5HWDuMIlUyGeauHN9S0bMHWviN16BF8L+dUF0vLnjTYS6I+0rnbR8SWOnWr6Y86fCKzUieSGChasOVrzA3Hjy11QNQse8nghB3pQURW7AdN44gaVf93v+mb8l/EoQBkDy0/kT9Q6sYc5D1HYD0YUodzcDUX1Hgyzw21vEFq3HgN9mKfL7kQgrPRfWFCuR4rZaFFXkXHso791FvqxFsYNPXYK2ODSIVCGvoQDZBINwD/26ka1Rfo8OZJ1eewtCxy5SpbIjMcWFHZcsxbgNjOU1z3+TfYSK2kaaGpNCT7oEif7BSoXcEUR82x2YU6LQpWHfFWx7NrZK5P4D2PZ6lA7gKaNUOtdMwVY6xU4CpUb6r9Ash7WxuXGiZU4shhmirk9nSsqVusx9WlNxIbBbWpRv2jY7B1dHo6O7aNq1vX0TRg0RL7yS/f/c8yQuGHUzjZ3HVHzwnQAOB9tXsq9C90TiShUTSLCandTYXRYkxCxVRCpdiJRWhWmpry3PSIK1FlyeUhiBAFS1O2QTc=
  - secure: UGDQehmmJdfeeeHk26nuFjVUINsahvxKNQuJW80ovudg/PsP/2WwzysjLzvSgjgKWFJttTClSJh4Ree59h9lOnt4xCa9H5IPNyHIrhxY6zxDdHmEc7p5rbULVL0WXmBnM+eB07YlnXxNlbhjh2orE8ZvaJKhyEu3yaiMBni6lFtO9AvOqpUTL86nVIyDH15GCBdS4FW8ejiy2hP9gpwivQeXnNDpb7Zb+4i/Y9P/c3tecEAn+9W+nhb4s95DAPti0S0kPZZHhNtf082xcK68aPt/pkM0MB8ONeyS66qxUUU1cNfGpKybPKj0jYBu4/KHFjHI2T1nLVifA6G0QYL7uTAvRKdz4ljYVFD6xB5R5BNXjLtUwQoCqtq+6l1tN5hNpjyUDeO+ftfSWbIi4GFyDJGhkXqxF76+MZoXi6rhzrBM8crefX6eVzAYQ6TqE7B3asoohKEfqy0XroHaOHwkmuuVbz+Fi2jxEJwptLZVXJdoudBVIy4DQcq1SqlPjgMrYn31HA8Lh+mxQ19I39Df9EdmvmuKpAwRABdWT68dH+F9ynhU5Apgedb0meE4GnVfww6f2rgsizM1bJXYPlWEpK/4Wt0DtZYLiHCh6b2YKvI2S5RoBylE7iHhUvWtozGwrFA8K1Sb1LkihYpIQukLweQGdo/0azr5y2aOW0XoHoo=
