language: node_js
sudo: false
node_js:
- 8.9.4
install:
- npm install
script:
- npm test
env:
  matrix:
  - secure: D9Zuygk1rSm0lY6FH6PY+r7ItpERkIeEbtIxqrmKcSpgZuVQ5njP16X2vLIA9pfqApoHu4bu+YhZKHgBK6q7wkYJNS52pasiRIWqAWRq+EPErZNedCZVyjBfIlrs5jyGH04BoVcupuRVnw7WN/5Y5ttbVMEoyGyTPrA17jUFAX+qMW3MkrWChBdsQJ2/fAisNE54mNJQqwju6vBonAZBPjfw/PLc0KmaT3jiW5hmMvBHVXIcZgUYVMKF5yTm9V67fntImfyuysj5nHdWOBAhpXIfcc+KEreo3PSZ3+igGgEcKR6yNFwpsjOlxzwVFAlKfjxZC24UedLXS+HaGagGGuKS3bd5c8gtOb8Z+aZCx9RGnwcb0c/H+vWmlMsApWrvxlevihRJdFQTXk1QKGfo7paVbvExQKAc7YjDy/TPdLeF+8MRn+RMOEBuLJo5ApqwvU3bLdr0VN/udtzgM/iRSZvz9NLkWwbUIvEMNsZhiMoo3sNXcL5s2h2qLzSDNQMNDJicqPjfGbb8Bds8lLb6hdKPEKQ6qIfd0S1fdNBwaMosIZknk2tUqMMkqlPjAP/aRATqw2bzyzcUMCIvnB+okERsns7LCrohNzFMy3v9HPpI5v9sOGx4VNXM/guUDb5EJtDgIq/KR5pOAFnj+Kqsn6m/Cw3BsWZEhsSh5raT07k=
  - secure: uJvsaPEItGteXS72d3jP5us7PvR0Uf5lqd5T7U8jmTAfnNYtI/1R+SurskXCLwz9PXbZ3mh2WdYLFx062C7vJkKAnQxDWUeLSt+fuBmhYiWsc0i9Qr2ikWImwDcg9ikmjxUJHM/YOA5C975YFevTHnFQIBMU40ErAUut3CUwfOEL70YkS6dvTxO1hy+psV5tJHfTAenBaMXHcGRZeVWr/MbnAqoIGqjBXkprt7IZtCBGYysFdY1tTHU9udeT7t7D5FqRTL3rN3r/Ib6b4652Xi2h/SDBv+v4x4/hHs3p1ADxekhqLumztGAbXtBxE0vRi2XEbe4EAsoGOy+gmmcdSTLlfU4uxh65aBHVYAOLSdXlmt+fGPH5IgdD1dd/L3p8R9JAyXx+1XSHtGfkGjjqfONKLcG2KKLHX1NTqyFdnsAPVv7A9kQJVSogdaVMB7ur2YsQR/4qI25bg7QtctgkGk5KgSnM5ZhHR4GBygJbZY0Qe2H8g8Ecx9BHlGtCMPpl2j4aBoGNK8lnz4NBjlNbaWqT3PWPAOH11rRfoxNSFP1Y6DoE5ZyVmYj28eioy0/qclSK9hpm4KO2H1HtkJ8138PqHBjuOpHMusEr8ILcxz9P3FgDkRP3wcZpluPK/7r6BI7tYMI+6kXM7VbtzpG6bOUFWHEEDBwXotZbe1aeSOI=
