language: node_js
sudo: false
node_js:
- 8.9.4
install:
- npm install
script:
- npm test
env:
  matrix:
  - secure: uJvsaPEItGteXS72d3jP5us7PvR0Uf5lqd5T7U8jmTAfnNYtI/1R+SurskXCLwz9PXbZ3mh2WdYLFx062C7vJkKAnQxDWUeLSt+fuBmhYiWsc0i9Qr2ikWImwDcg9ikmjxUJHM/YOA5C975YFevTHnFQIBMU40ErAUut3CUwfOEL70YkS6dvTxO1hy+psV5tJHfTAenBaMXHcGRZeVWr/MbnAqoIGqjBXkprt7IZtCBGYysFdY1tTHU9udeT7t7D5FqRTL3rN3r/Ib6b4652Xi2h/SDBv+v4x4/hHs3p1ADxekhqLumztGAbXtBxE0vRi2XEbe4EAsoGOy+gmmcdSTLlfU4uxh65aBHVYAOLSdXlmt+fGPH5IgdD1dd/L3p8R9JAyXx+1XSHtGfkGjjqfONKLcG2KKLHX1NTqyFdnsAPVv7A9kQJVSogdaVMB7ur2YsQR/4qI25bg7QtctgkGk5KgSnM5ZhHR4GBygJbZY0Qe2H8g8Ecx9BHlGtCMPpl2j4aBoGNK8lnz4NBjlNbaWqT3PWPAOH11rRfoxNSFP1Y6DoE5ZyVmYj28eioy0/qclSK9hpm4KO2H1HtkJ8138PqHBjuOpHMusEr8ILcxz9P3FgDkRP3wcZpluPK/7r6BI7tYMI+6kXM7VbtzpG6bOUFWHEEDBwXotZbe1aeSOI=
deploy:
  provider: heroku
  api_key:
    secure: AHeoOi52K1toRBC0TWSe4Fx8zRN6B1fMQFJkn9mWzRZiPYgHXMHJGAcxE0QEuMpL7mvwmbw3YfsJ4r0Qv2XmFdDx0A/2MokyTD6h6lBjKJM5zC8NzNyF4Vzydi4uFmY2dDWycAsfCB4bkllEzwskkNqQX/u3SbW3qJ5KuksrkM9nGsN2zBJGXdavtStR+RLEGDNIuEYbdLbxWVy3C3fAZYLheYRU26wF46d/Wq7Pohr6pqqVyOPcae9G8qN6KaZ2XIQm8YXwObwSI3oTGeEZ/t446WfyNO6SwwQCJAhLOLcm77A0gSgoLlfj0KXJpKRHybk7PMd6WOADQPgx8YQ/rotUfKVAlE2HygUuZeqBJLwTSlLBIn96OXkQw4OTUxtt60oxOUZeMwFCFDf9yGxhI6z96vCR68gfv+/AhWFQszwe3G3Sr6j6m95gfikyDPemd4JxncpCzXVriKt771Q70zoitkp1PM9V+7X2/Kjik4GRz4uWNwB3AR1RJ4WWrvWi0Tul23sKRvK+oaQG/K0Ildjj5Q9YVrKCCxB89JcZ9da3AEZMUrBss5KByuIJMA5gyYXdvU7VqZU84shEF5N2dakzqli12Vd81QGKh4BVvSII52mzSPCP9sdCJtgm3O7cmznGqWN9EuEIlpofnpBnINgykAIyWu3tnBqLugrF8yg=
  app: ft-tech-test
  on:
    repo: Leigan0/test
